/* eslint-disable prettier/prettier */

import { v4 as uuidv4 } from 'uuid';

import { MESSAGE_STATUS, MESSAGE_TYPE } from '@/common';
import { Message } from '@/interfaces/response';

export const fakeMessages: Message[] = [
  {
    id: uuidv4(),
    roomId: 'room-1',
    senderId: 'alice',
    content: 'Hi! How can I help?',
    type: MESSAGE_TYPE.TEXT,
    createdAt: '2025-10-29T09:10:00Z',
    readBy: ['you'],
    status: MESSAGE_STATUS.DELIVERED,
  },
  {
    id: uuidv4(),
    roomId: 'room-1',
    senderId: 'you',
    content: 'I need a quick demo layout.',
    type: MESSAGE_TYPE.TEXT,
    createdAt: '2025-10-29T09:11:00Z',
    readBy: ['you', 'alice'],
    status: MESSAGE_STATUS.READ,
  },
  {
    id: uuidv4(),
    roomId: 'room-1',
    senderId: 'alice',
    content: 'Sure — here you go 👇',
    type: MESSAGE_TYPE.TEXT,
    createdAt: '2025-10-29T09:12:00Z',
    readBy: ['you'],
    status: MESSAGE_STATUS.DELIVERED,
  },
  {
    id: uuidv4(),
    roomId: 'room-1',
    senderId: 'alice',
    content: 'https://i.imgur.com/AIUXo7A.png',
    type: MESSAGE_TYPE.IMAGE,
    createdAt: '2025-10-29T09:12:30Z',
    readBy: ['you'],
    status: MESSAGE_STATUS.DELIVERED,
  },
  {
    id: uuidv4(),
    roomId: 'room-1',
    senderId: 'you',
    content: 'Wow, that looks great. Thanks! 🙌',
    type: MESSAGE_TYPE.TEXT,
    createdAt: '2025-10-29T09:14:00Z',
    readBy: ['you', 'alice'],
    status: MESSAGE_STATUS.READ,
  },
  {
    id: uuidv4(),
    roomId: 'room-1',
    senderId: 'alice',
    content: 'No problem! 😊 Anything else you need?',
    type: MESSAGE_TYPE.TEXT,
    createdAt: '2025-10-29T09:15:00Z',
    readBy: ['you'],
    status: MESSAGE_STATUS.DELIVERED,
  },
  {
    id: uuidv4(),
    roomId: 'room-1',
    senderId: 'you',
    content: 'Maybe a quick dark theme preview?',
    type: MESSAGE_TYPE.TEXT,
    createdAt: '2025-10-29T09:16:00Z',
    readBy: ['you', 'alice'],
    status: MESSAGE_STATUS.READ,
  },
  {
    id: uuidv4(),
    roomId: 'room-1',
    senderId: 'alice',
    content: 'Sure thing — give me 2 minutes 🕒',
    type: MESSAGE_TYPE.TEXT,
    createdAt: '2025-10-29T09:16:45Z',
    readBy: ['you'],
    status: MESSAGE_STATUS.SENT,
  },
  {
    id: uuidv4(),
    roomId: 'room-1',
    senderId: 'alice',
    content: 'https://i.imgur.com/xP3mRpD.jpeg',
    type: MESSAGE_TYPE.IMAGE,
    createdAt: '2025-10-29T09:18:00Z',
    readBy: ['you'],
    status: MESSAGE_STATUS.DELIVERED,
  },
  {
    id: uuidv4(),
    roomId: 'room-1',
    senderId: 'you',
    content: '🔥🔥🔥 That’s perfect!',
    type: MESSAGE_TYPE.TEXT,
    createdAt: '2025-10-29T09:18:45Z',
    readBy: ['you', 'alice'],
    status: MESSAGE_STATUS.READ,
  },
  {
    id: uuidv4(),
    roomId: 'room-1',
    senderId: 'alice',
    content: 'Glad you like it 😄',
    type: MESSAGE_TYPE.TEXT,
    createdAt: '2025-10-29T09:19:30Z',
    readBy: ['you'],
    status: MESSAGE_STATUS.READ,
  },
  {
    id: uuidv4(),
    roomId: 'room-1',
    senderId: 'you',
    content:
      'Let’s test a long message to see wrapping in chat bubbles. Sometimes users send longer texts so we should ensure it breaks lines properly and stays readable even on smaller screens.',
    type: MESSAGE_TYPE.TEXT,
    createdAt: '2025-10-29T09:21:00Z',
    readBy: ['you', 'alice'],
    status: MESSAGE_STATUS.READ,
  },
  {
    id: uuidv4(),
    roomId: 'room-1',
    senderId: 'alice',
    content: 'Yep, looks good! I’ll mark this conversation as complete ✅',
    type: MESSAGE_TYPE.TEXT,
    createdAt: '2025-10-29T09:22:30Z',
    readBy: ['you'],
    status: MESSAGE_STATUS.DELIVERED,
  },
  {
    id: uuidv4(),
    roomId: 'room-1',
    senderId: 'alice',
    content: 'Yep, looks good! I’ll mark this conversation as complete ✅',
    type: MESSAGE_TYPE.TEXT,
    createdAt: '2025-10-29T09:22:30Z',
    readBy: ['you'],
    status: MESSAGE_STATUS.DELIVERED,
  },
  {
    id: uuidv4(),
    roomId: 'room-1',
    senderId: 'alice',
    content: 'Yep, looks good! I’ll mark this conversation as complete ✅',
    type: MESSAGE_TYPE.TEXT,
    createdAt: '2025-10-29T09:22:30Z',
    readBy: ['you'],
    status: MESSAGE_STATUS.DELIVERED,
  },
  {
    id: uuidv4(),
    roomId: 'room-1',
    senderId: 'alice',
    content: 'Yep, looks good! I’ll mark this conversation as complete ✅',
    type: MESSAGE_TYPE.TEXT,
    createdAt: '2025-10-29T09:22:30Z',
    readBy: ['you'],
    status: MESSAGE_STATUS.DELIVERED,
  },
  {
    id: uuidv4(),
    roomId: 'room-1',
    senderId: 'alice',
    content: 'Yep, looks good! I’ll mark this conversation as complete ✅',
    type: MESSAGE_TYPE.TEXT,
    createdAt: '2025-10-29T09:22:30Z',
    readBy: ['you'],
    status: MESSAGE_STATUS.DELIVERED,
  },
  {
    id: uuidv4(),
    roomId: 'room-1',
    senderId: 'alice',
    content: 'Yep, looks good! I’ll mark this conversation as complete ✅',
    type: MESSAGE_TYPE.TEXT,
    createdAt: '2025-10-29T09:22:30Z',
    readBy: ['you'],
    status: MESSAGE_STATUS.DELIVERED,
  },
];
