/* eslint-disable prettier/prettier */
export const GLOBAL_ACCOUNT_INFO = 'GLOBAL_ACCOUNT_INFO';

export const GLOBAL_CHAT_ROOM_KEY = 'GLOBAL_CHAT_ROOM_KEY';

export const GLOBAL_SOCKET_STATUS = 'GLOBAL_SOCKET_STATUS';

export const GLOBAL_SOCKET_INIT = 'GLOBAL_SOCKET_INIT';

export const CHAT_FORWARD_MODAL = 'CHAT_FORWARD_MODAL';

export const CHAT_DELETE_MODE = 'CHAT_DELETE_MODE';
