/* eslint-disable prettier/prettier */
export const GLOBAL_ACCOUNT_INFO = 'GLOBAL_ACCOUNT_INFO';

export const GLOBAL_SESSION_INFO = 'GLOBAL_SESSION_INFO';

export const GLOBAL_CHAT_ROOM_KEY = 'GLOBAL_CHAT_ROOM_KEY';

export const GLOBAL_RECENT_CHAT_ROOMS = 'GLOBAL_RECENT_CHAT_ROOMS';

export const GLOBAL_SOCKET_STATUS = 'GLOBAL_SOCKET_STATUS';

export const GLOBAL_SOCKET_INIT = 'GLOBAL_SOCKET_INIT';

export const GLOBAL_SELECTED_MODE_CHAT = 'GLOBAL_SELECTED_MODE_CHAT';

export const TIME_OUT_REQUEST = 60 * 1000; // 60 seconds
