/* eslint-disable prettier/prettier */
import { v4 as uuidv4 } from 'uuid';

import { ChatRoom } from '@/interfaces/response';
import { CHAT_ROOM_TYPE } from '@/common';

export const fakeChatRooms: ChatRoom[] = [
  {
    id: uuidv4(),
    name: 'General',
    description: 'Chung cho mọi người',
    members: [uuidv4(), uuidv4(), uuidv4()],
    messages: ['m1', 'm2'],
    avatarUrl: '',
    isPrivate: false,
    ownerId: uuidv4(),
    lastMessageId: 'm2',
    unreadCount: 2,
    type: CHAT_ROOM_TYPE.GROUP,
    topic: 'Trao đổi chung',
    pinnedMessageIds: [],
    createdAt: '2024-10-29T10:00:00Z',
    updatedAt: '2024-10-29T10:10:00Z',
  },
  {
    id: uuidv4(),
    name: 'Bob',
    members: [uuidv4(), uuidv4()],
    messages: [uuidv4()],
    isPrivate: true,
    ownerId: 'me',
    lastMessageId: 'm3',
    unreadCount: 0,
    type: CHAT_ROOM_TYPE.DIRECT,
    createdAt: '2024-10-29T09:00:00Z',
    updatedAt: '2024-10-29T10:00:00Z',
  },
  {
    id: uuidv4(),
    name: 'Frontend Team',
    description: 'Thảo luận về UI/UX',
    members: [uuidv4(), uuidv4(), uuidv4(), uuidv4()],
    messages: [uuidv4(), uuidv4()],
    avatarUrl: '',
    isPrivate: false,
    ownerId: uuidv4(),
    lastMessageId: 'm5',
    unreadCount: 5,
    type: CHAT_ROOM_TYPE.GROUP,
    topic: 'React, Tailwind, Design',
    pinnedMessageIds: [],
    createdAt: '2024-10-28T08:00:00Z',
    updatedAt: '2024-10-29T08:30:00Z',
  },
  {
    id: uuidv4(),
    name: 'Support',
    description: 'Hỗ trợ khách hàng',
    members: [uuidv4(), uuidv4()],
    messages: [uuidv4()],
    avatarUrl: '',
    isPrivate: true,
    ownerId: uuidv4(),
    lastMessageId: 'm6',
    unreadCount: 1,
    type: CHAT_ROOM_TYPE.DIRECT,
    topic: 'Hỗ trợ kỹ thuật',
    pinnedMessageIds: [],
    createdAt: '2024-10-27T12:00:00Z',
    updatedAt: '2024-10-29T09:00:00Z',
  },
  {
    id: uuidv4(),
    name: 'Random',
    description: 'Nơi tám chuyện linh tinh',
    members: [uuidv4(), uuidv4(), uuidv4()],
    messages: [uuidv4(), uuidv4(), uuidv4()],
    avatarUrl: '',
    isPrivate: false,
    ownerId: uuidv4(),
    lastMessageId: 'm9',
    unreadCount: 0,
    type: CHAT_ROOM_TYPE.GROUP,
    topic: 'Chuyện phiếm',
    pinnedMessageIds: [],
    createdAt: '2024-10-25T15:00:00Z',
    updatedAt: '2024-10-29T10:00:00Z',
  },
  {
    id: uuidv4(),
    name: 'General',
    description: 'Chung cho mọi người',
    members: [uuidv4(), uuidv4(), uuidv4()],
    messages: ['m1', 'm2'],
    avatarUrl: '',
    isPrivate: false,
    ownerId: uuidv4(),
    lastMessageId: 'm2',
    unreadCount: 2,
    type: CHAT_ROOM_TYPE.GROUP,
    topic: 'Trao đổi chung',
    pinnedMessageIds: [],
    createdAt: '2024-10-29T10:00:00Z',
    updatedAt: '2024-10-29T10:10:00Z',
  },
  {
    id: uuidv4(),
    name: 'Bob',
    members: [uuidv4(), uuidv4()],
    messages: [uuidv4()],
    isPrivate: true,
    ownerId: 'me',
    lastMessageId: 'm3',
    unreadCount: 0,
    type: CHAT_ROOM_TYPE.DIRECT,
    createdAt: '2024-10-29T09:00:00Z',
    updatedAt: '2024-10-29T10:00:00Z',
  },
  {
    id: uuidv4(),
    name: 'Frontend Team',
    description: 'Thảo luận về UI/UX',
    members: [uuidv4(), uuidv4(), uuidv4(), uuidv4()],
    messages: [uuidv4(), uuidv4()],
    avatarUrl: '',
    isPrivate: false,
    ownerId: uuidv4(),
    lastMessageId: 'm5',
    unreadCount: 5,
    type: CHAT_ROOM_TYPE.GROUP,
    topic: 'React, Tailwind, Design',
    pinnedMessageIds: [],
    createdAt: '2024-10-28T08:00:00Z',
    updatedAt: '2024-10-29T08:30:00Z',
  },
  {
    id: uuidv4(),
    name: 'Support',
    description: 'Hỗ trợ khách hàng',
    members: [uuidv4(), uuidv4()],
    messages: [uuidv4()],
    avatarUrl: '',
    isPrivate: true,
    ownerId: uuidv4(),
    lastMessageId: 'm6',
    unreadCount: 1,
    type: CHAT_ROOM_TYPE.DIRECT,
    topic: 'Hỗ trợ kỹ thuật',
    pinnedMessageIds: [],
    createdAt: '2024-10-27T12:00:00Z',
    updatedAt: '2024-10-29T09:00:00Z',
  },
  {
    id: uuidv4(),
    name: 'Random',
    description: 'Nơi tám chuyện linh tinh',
    members: [uuidv4(), uuidv4(), uuidv4()],
    messages: [uuidv4(), uuidv4(), uuidv4()],
    avatarUrl: '',
    isPrivate: false,
    ownerId: uuidv4(),
    lastMessageId: 'm9',
    unreadCount: 0,
    type: CHAT_ROOM_TYPE.GROUP,
    topic: 'Chuyện phiếm',
    pinnedMessageIds: [],
    createdAt: '2024-10-25T15:00:00Z',
    updatedAt: '2024-10-29T10:00:00Z',
  },
  {
    id: uuidv4(),
    name: 'General',
    description: 'Chung cho mọi người',
    members: [uuidv4(), uuidv4(), uuidv4()],
    messages: ['m1', 'm2'],
    avatarUrl: '',
    isPrivate: false,
    ownerId: uuidv4(),
    lastMessageId: 'm2',
    unreadCount: 2,
    type: CHAT_ROOM_TYPE.GROUP,
    topic: 'Trao đổi chung',
    pinnedMessageIds: [],
    createdAt: '2024-10-29T10:00:00Z',
    updatedAt: '2024-10-29T10:10:00Z',
  },
  {
    id: uuidv4(),
    name: 'Bob',
    members: [uuidv4(), uuidv4()],
    messages: [uuidv4()],
    isPrivate: true,
    ownerId: 'me',
    lastMessageId: 'm3',
    unreadCount: 0,
    type: CHAT_ROOM_TYPE.DIRECT,
    createdAt: '2024-10-29T09:00:00Z',
    updatedAt: '2024-10-29T10:00:00Z',
  },
  {
    id: uuidv4(),
    name: 'Frontend Team',
    description: 'Thảo luận về UI/UX',
    members: [uuidv4(), uuidv4(), uuidv4(), uuidv4()],
    messages: [uuidv4(), uuidv4()],
    avatarUrl: '',
    isPrivate: false,
    ownerId: uuidv4(),
    lastMessageId: 'm5',
    unreadCount: 5,
    type: CHAT_ROOM_TYPE.GROUP,
    topic: 'React, Tailwind, Design',
    pinnedMessageIds: [],
    createdAt: '2024-10-28T08:00:00Z',
    updatedAt: '2024-10-29T08:30:00Z',
  },
  {
    id: uuidv4(),
    name: 'Support',
    description: 'Hỗ trợ khách hàng',
    members: [uuidv4(), uuidv4()],
    messages: [uuidv4()],
    avatarUrl: '',
    isPrivate: true,
    ownerId: uuidv4(),
    lastMessageId: 'm6',
    unreadCount: 1,
    type: CHAT_ROOM_TYPE.DIRECT,
    topic: 'Hỗ trợ kỹ thuật',
    pinnedMessageIds: [],
    createdAt: '2024-10-27T12:00:00Z',
    updatedAt: '2024-10-29T09:00:00Z',
  },
  {
    id: uuidv4(),
    name: 'Random',
    description: 'Nơi tám chuyện linh tinh',
    members: [uuidv4(), uuidv4(), uuidv4()],
    messages: [uuidv4(), uuidv4(), uuidv4()],
    avatarUrl: '',
    isPrivate: false,
    ownerId: uuidv4(),
    lastMessageId: 'm9',
    unreadCount: 0,
    type: CHAT_ROOM_TYPE.GROUP,
    topic: 'Chuyện phiếm',
    pinnedMessageIds: [],
    createdAt: '2024-10-25T15:00:00Z',
    updatedAt: '2024-10-29T10:00:00Z',
  },
];
